export class Entity {
  constructor(public newGroupId?: number,
              public newGroupName?: string,
              public currentGroupId?: number,
              public currentGroupName?: string,
              public type?: string,
              public cowId?: number,
              public animalId?: string,
              public eventId?: number,
              public deletable?: boolean,
              public lactationNumber?: number,
              public daysInLactation?: number,
              public ageInDays?: number,
              public startDateTime?: number,
              public reportingDateTime?: number,
              public healthIndex?: number,
              public endDate?: number,
              public minValueDateTime?: number,
              public heatIndexPeak?: string,
              public alertType?: string,
              public duration?: number,
              public originalStartDateTime?: string,
              public birthDateCalculated?: boolean,
              public endDateTime?: any,
              public destinationGroup?: number,
              public sire?: any,
              public destinationGroupName?: string,
              public daysInPregnancy?: number,
              public breedingNumber?: any,
              public isOutOfBreedingWindow?: any,
              public interval?: number,
              public calvingEase?: any,
              public cowEntryStatus?: any,
              public oldLactationNumber?: any,
              public newborns?: boolean) {
  }
}
